paths: 
  /api/products:
    get:
      summary: "Consultar todos los productos" 
      tags: 
        - "Product"
      responses:
        "200":
          description: "Productos obtenidos correctamente"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: "Error al obtener los productos"
    post:
      summary: "Agregar un producto" 
      tags: 
        - "Product"
      requestBody:
        $ref: "#/components/requestBodies/updateProduct"
      responses:
        "200":
          description: "Producto creado correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: "Error al crear el producto"

  /api/products/{pid}:
    get:
      summary: "Consultar un producto por id" 
      tags: 
        - "Product"
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: "Id del producto"
      responses:
        "200":
          description: "Producto obtenido correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Producto no encontrado"
        "500":
          description: "Error al obtener el producto"
    put:
      summary: "Actualizar un producto por id" 
      tags: 
        - "Product"
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: "Id del producto"
      requestBody:
        $ref: "#/components/requestBodies/updateProduct"
      responses:
        "200":
          description: "Producto actualizado correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Producto no encontrado"
        "500":
          description: "Error al actualizar el producto"
    delete:
      summary: "Eliminar un producto por id" 
      tags: 
        - "Product"
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: "Id del producto"
      responses:
        "200":
          description: "Producto eliminado correctamente"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Producto no encontrado"
        "500":
          description: "Error al eliminar el producto"
                
components:
  schemas:
    Product:
      type: object
      properties:
        title:
          type: string
          required: true
        description:
          type: string
          required: true
        price:
          type: number
          required: true
          format: float
        thumbnail:
          type: string
          required: true
        code:
          type: string
          required: true
        stock:
          type: number
          required: true
          format: float
        status:
          type: boolean
          default: true
        category:
          type: string
          required: true
        owner:
          type: string
      example:
        title: "Producto 1"
        description: "Descripción del producto 1"
        price: 100
        thumbnail: "https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png"
        code: "1234"
        stock: 10
        status: true
        category: "Autos"
        owner: "creador@mail.com"

  requestBodies:
    updateProduct:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
      required: true